### ISSUE TITLE
Can this SDK be used with .Net Standard ?

### ISSUE THREAD

**Issue by rcoode** [salesforce-marketingcloud/FuelSDK-CSharp#71]
I'm trying to use the SDK with a .Net Standard project and have added all the the required packages but when I attempt to create a new **ETClient** I get the following error message

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=TransportSecurityBindingElement.BuildChannelFactoryCore is not supported.
  Source=System.Private.ServiceModel
  StackTrace:
   at System.ServiceModel.Channels.TransportSecurityBindingElement.BuildChannelFactoryCore[TChannel](BindingContext context)
   at System.ServiceModel.Channels.SecurityBindingElement.BuildChannelFactory[TChannel](BindingContext context)
   at System.ServiceModel.Channels.Binding.BuildChannelFactory[TChannel](BindingParameterCollection parameters)
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__79.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__78.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ClientBase`1.get_Channel()
   at System.ServiceModel.ClientBase`1.get_InnerChannel()
   at FuelSDK.ETClient..ctor(NameValueCollection parameters, RefreshState refreshState)
   at MFL.DealerPortal.ExactTarget.Services.ExactTargetService..ctor(IOptions`1 exactTargetConfig) in C:\Projects\MFL.DealerPortal\MFL.DealerPortal.ExactTarget\Services\ExactTargetService.cs:line 19
```
Can I resolve this or is .NET Standard not supported. If not then do you have an alternative API I can use to maintain subscriber lists for ExactTarget

Thanks

**Comment by luebster** [comment]
Yeah, this is a serious problem. We're moving all our clients' websites to .Net Core 2.* and I just discovered that this SDK is not compatible.

Rather than breaking all our sites, my only solution at this point seems to be building a web service using .NET 4.7 and having each site call it to do the API work.

**Comment by queen-of-code** [comment]
Hi, any traction on this? It would be very useful to my team as well.

**Comment by Jetski5822** [comment]
Hey all - I just took a look at the code, and looks like upgrading would be pretty straightforward.

I would say, 2 days effort to upgrade and a few to refactor.

If you want it done, I don’t mind giving it a punt, but it would totally be not tested as I no longer have access to ET. So would rely on your teams to test it.

**Comment by queen-of-code** [comment]
I would be _delighted_ to test it if you make a cut. However, know that you may run into https://github.com/dotnet/wcf/issues/1257 which is apparently targeted into the dotnet core 3.0 release.

**Comment by Nirmalatatikonda** [comment]
We are interested in the .net standard version too, what is needed to accomplish this?

**Comment by dorkalord** [comment]
Here is a gentleman who was nice enough to port it 
https://github.com/pepperpark/FuelSDK-CSharp
